### PR TITLE
Customers main page with a list of customers data

### PR DESCRIPTION
**Pull request by chunweng428**
Customer page with customers list, create, update and delete function, filter customer

### CODE REVIEW

**Comment by MasterODST** [comment]
Interesting you used an active entry filter to speed up the process for searching for customers based on their name ingenious .

**Comment by MasterODST** [comment]
May I ask why the search method work using case sensitive search parameters??

**Comment by chunweng428** [comment]
I make the filter with case sensitive is because it could help to speed up the searching process.

**Comment by tanjunlem** [comment]
I think this function would really helpful to the customer's experience to the system. Well done

**Review by TeckYong — APPROVED** [review]

**Review by tanjunlem — APPROVED** [review]
Well doe.

**Pull request merged**
